name: Private Checkout
description: Check out another private repository in the same organization or enterprise
author: Jon Jensen
inputs:
  repository:
    description: Repository name with owner, e.g. `my-org/my-repo`
    required: true
  ref:
    description: Branch, tag or SHA to check out, e.g. `main`
    required: false
    default: "main"
  path:
    description: Relative path under `$GITHUB_WORKSPACE` to place the repository, e.g. `./my-repo`
    required: false
    default: "."
  action-path:
    description: Subdirectory containing an `action.yml` or `Dockerfile`
    required: false
outputs:
  failure-reason:
    description: Reason the checkout failed. Mainly used for testing, since we also emit an error message for the user.
    value: ${{ steps.validate-inputs.outputs.failure-reason || steps.copy-checkout.outputs.failure-reason || '' }}
runs:
  using: composite
  steps:
    - name: Validate inputs
      id: validate-inputs
      shell: bash
      env:
        repository: ${{ inputs.repository }}
        ref: ${{ inputs.ref }}
        checkout_path: ${{ inputs.path }}
        action_path: ${{ inputs.action-path }}
      run: |
        # validate inputs

        die() {
          failure_reason="$1"
          echo "failure-reason=$failure_reason" >> $GITHUB_OUTPUT
          echo "::error::$1"
          exit 1
        }
        [[ "$repository" =~ ^[a-zA-Z0-9_\-]+/[a-zA-Z0-9._\-]+$ ]] || die "Invalid repository format, expected 'owner/name', got '$repository'"
        true
    - name: Prepare checkout action
      shell: bash
      run: |
        mkdir -p .tmp-checkout-private-repo &&
        cat <<'CHECKOUT_PRIVATE_REPO_EOF' >.tmp-checkout-private-repo/action.yml
        runs:
          using: composite
          steps:
          - name: Trigger repository checkout
            if: false
            uses: ${{ toJSON(format('{0}{1}@{2}', inputs.repository, inputs.action-path && format('/{0}', inputs.action-path) || '', inputs.ref)) }}
        CHECKOUT_PRIVATE_REPO_EOF
    - name: Check out repository
      id: checkout
      continue-on-error: true
      uses: ./.tmp-checkout-private-repo
    - name: Clean up checkout action
      if: always()
      shell: bash
      run: rm -rf .tmp-checkout-private-repo
    - name: Copy checkout to path
      id: copy-checkout
      shell: bash
      env:
        repository: ${{ inputs.repository }}
        ref: ${{ inputs.ref }}
        checkout_path: ${{ inputs.path }}
        checkout_step_failed: ${{ steps.checkout.outcome == 'failure' }}
      run: |
        # copy files

        die() {
          failure_reason="$1"
          echo "failure-reason=$failure_reason" >> $GITHUB_OUTPUT
          echo "::error::$1"
          exit 1
        }
        expected_checkout_path="$GITHUB_ACTION_PATH/../../../$repository/$ref"
        echo "LS of expected repo dir ($GITHUB_ACTION_PATH/../../..):"
        ls -all "$GITHUB_ACTION_PATH/../../.." || true
        echo "LS of everything in there"
        ls -all $GITHUB_ACTION_PATH/../../../* || true
        echo "LS of expected_checkout_path:"
        ls -all "$expected_checkout_path" || true

        [[ -d "$expected_checkout_path" ]] || die "Failed to check out $repository@$ref. Confirm that the repository is accessible and that the ref is valid."

        # if the step failed, but the files are there, it just means actions/runner puked on the lack of action.yml or Dockerfile.
        # so emit a helpful hint
        [[ "$checkout_step_failed" == "true" ]] && {
          echo "::notice::You can suppress \"Can't find 'action.yml' ...\" errors by creating a dummy action file. Learn more: https://github.com/jenseng/private-checkout#can-i-disable-the-cant-find-actionyml-errors"
        }
        target_path="$GITHUB_WORKSPACE"
        if [[ -n "$checkout_path" ]]; then
          target_path="$GITHUB_WORKSPACE/$checkout_path"
        fi
        mkdir -p "$target_path"
        if which rsync >/dev/null 2>&1; then
          rsync -a "$expected_checkout_path/" "$target_path/"
        else
          shopt -s dotglob
          cp -a "$expected_checkout_path/"* "$target_path/"
        fi
